customhost = "employeedb2.cvtgddrlheke.us-east-1.rds.amazonaws.com"
customuser = "adminuser"
custompass = "Admin123"
customdb = "employeedb2"
custombucket = "product-employee"
customregion = "us-east-1"
